name: Build and Push Docker Image to ECR

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push-image-to-ecr:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{secrets.REGISTRY}}/coding-jjun/giftogether
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

          flavor: |
            latest=true
      
      - name: test metatags
        run: |
            echo "steps.meta.outputs.tags=${{ steps.meta.outputs.tags }}"
            echo "steps.meta.outputs.labels=${{ steps.meta.outputs.labels }}"
            echo "bake-file: ${{steps.meta.outputs.bake-file}}"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
          push: true
